language: cpp
sudo: required
dist: trusty

os: linux

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt57-trusty
  - sudo apt-get update -qq
  - wget https://nixos.org/releases/patchelf/patchelf-0.9/patchelf-0.9.tar.bz2
  - tar xf patchelf-0.9.tar.bz2
  - cd patchelf-*/ 
  - ./configure
  - make -j7
  - sudo make install
  - cd -
  - ID=$(wget -q https://api.travis-ci.org/repos/probonopd/appimagetool/builds -O - | head -n 1 | sed -e 's|}|\n|g' | grep '"result":0' | head -n 1 | sed -e 's|,|\n|g' | grep '"id"' | cut -d ":" -f 2)
  - URL=$(wget -q "http://archive.travis-ci.org/jobs/$((ID+1))/log.txt" -O - | grep "https://transfer.sh/.*/appimagetool" | tail -n 1 | sed -e 's|\r||g')
  - if [ -z "$URL" ] ; then ; URL=$(wget -q "http://archive.travis-ci.org/jobs/$((ID+2))/log.txt" -O - | grep "https://transfer.sh/.*/appimagetool" | tail -n 1 | sed -e 's|\r||g') ; fi
  - sudo wget -c "$URL" -O /usr/local/bin/appimagetool
  - sudo chmod a+x /usr/local/bin/appimagetool
  
install:
  - sudo apt-get -y install qt57base binutils

script:
  - source /opt/qt57/bin/qt57-env.sh
  - /opt/qt57/bin/qmake linuxdeployqt.pro
  - make -j7
  - mkdir -p linuxdeployqt.AppDir/usr/bin/
  - cp /usr/local/bin/patchelf linuxdeployqt.AppDir/usr/bin/
  - cp /usr/local/bin/appimagetool linuxdeployqt.AppDir/usr/bin/
  - # cp $(which qmlimportscanner) linuxdeployqt.AppDir/ # use the one from the Qt to be bundled instead
  - cp ./linuxdeployqt/linuxdeployqt linuxdeployqt.AppDir/linuxdeployqt
  - ./linuxdeployqt/linuxdeployqt linuxdeployqt.AppDir/linuxdeployqt -verbose=3 -appimage
  - mv linuxdeployqt.AppDir.AppImage linuxdeployqt.AppImage
  - curl --upload-file ./linuxdeployqt.AppImage https://transfer.sh/linuxdeployqt.appimage
