language: cpp
sudo: required
dist: trusty

os: linux

env:
  global:
    - DISPLAY=:99

script:
  - ./tests/travis.sh

#after_success:
#  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
#  - bash ./upload.sh ./linuxdeployqt-*.AppImage*

after_script:
  - "xpra stop :99"

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
