language: cpp
sudo: required
dist: trusty

addons:
  apt:
    packages:
      - g++-6
    sources: &sources
      - ubuntu-toolchain-r-test

os: linux
env: COMPILER=g++-6

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt511-trusty
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt51tools qt51base

script:
  - source /opt/qt57/bin/qt51-env.sh
  - /opt/qt57/bin/qmake linuxdeployqt.pro
  - make CXX='g++-6' -j7
  - find .
  - strip linuxdeployqt/linuxdeployqt
  - curl --upload-file ./linuxdeployqt/linuxdeployqt https://transfer.sh/linuxdeployqt
  - mkdir linuxdeployqt.AppDir ; cp linuxdeployqt/linuxdeployqt linuxdeployqt.AppDir/AppRun
  - linuxdeployqt/linuxdeployqt linuxdeployqt.AppDir/AppRun
