language: cpp
sudo: required
dist: trusty

os: linux

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt57-trusty
  - sudo apt-get update -qq
  - wget https://nixos.org/releases/patchelf/patchelf-0.9/patchelf-0.9.tar.bz2
  - tar xf patchelf-0.9.tar.bz2
  - cd patchelf-*/ 
  - ./configure
  - make -j7
  - sudo make install
  - cd -
  - sudo wget -c "https://github.com/probonopd/AppImageKit/releases/download/6/AppImageAssistant_6-x86_64.AppImage" -O /usr/local/bin/AppImageAssistant

install:
  - sudo apt-get -y install qt57base

script:
  - source /opt/qt57/bin/qt57-env.sh
  - /opt/qt57/bin/qmake linuxdeployqt.pro
  - make -j7
  - mkdir -p linuxdeployqt.AppDir/usr/bin/
  - cp /usr/local/bin/patchelf linuxdeployqt.AppDir/usr/bin/
  - cp ./linuxdeployqt/linuxdeployqt linuxdeployqt.AppDir/linuxdeployqt
  - ./linuxdeployqt/linuxdeployqt linuxdeployqt.AppDir/linuxdeployqt -verbose=3 -appimage
  - find .
  # - curl --upload-file ./linuxdeployqt/linuxdeployqt https://transfer.sh/linuxdeployqt
